### ISSUE TITLE
!weather command to check weather

### ISSUE THREAD

**Issue by FrankWhoee** [VikingsDev/Dentaku#43]
Accepts location and time as params. location defaults to burnaby and time defaults to now

example usage:

!weather -L burnaby -t tommorow

!weather -t tommorow

!weather -L burnaby

!weather

**Comment by georgecwan** [comment]
I will do this then fail this

**Comment by FrankWhoee** [comment]
u got this!

**Comment by FrankWhoee** [comment]
Resolved by #63
