### ISSUE TITLE
!search command

### ISSUE THREAD

**Issue by ratanawang** [VikingsDev/Dentaku#89]
- returns Wikipedia page (or image¿) on a specific subject when called 
- would work like this:
> Person: !search dogs
> VikingsDev: Here is some information about dogs: [insert Wikipedia dog link]

(maybe use frank's build day project somehow¿ idk)

**Comment by georgecwan** [comment]
This is literally !weather except !wikipedia

**Comment by InhoStudios** [comment]
added gsearch as a search command which searches google and returns the first link
